// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using familyTreeApi.Data;

#nullable disable

namespace familyTreeApi.Migrations
{
    [DbContext(typeof(FamilyTreeDbContext))]
    [Migration("20241123101417_Added_Seeding_For_Relations_Table")]
    partial class Added_Seeding_For_Relations_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("familyTreeApi.Models.Relations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RelationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Relations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DisplayName = "Father",
                            IsDeleted = false,
                            RelationName = "father"
                        },
                        new
                        {
                            Id = 2L,
                            DisplayName = "Mother",
                            IsDeleted = false,
                            RelationName = "mother"
                        },
                        new
                        {
                            Id = 3L,
                            DisplayName = "Sibling",
                            IsDeleted = false,
                            RelationName = "sibling"
                        },
                        new
                        {
                            Id = 4L,
                            DisplayName = "Child",
                            IsDeleted = false,
                            RelationName = "child"
                        });
                });

            modelBuilder.Entity("familyTreeApi.Models.UserRelations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long>("RelationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("DeletedUserId");

                    b.HasIndex("ModifiedUserId");

                    b.HasIndex("RelationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRelations");
                });

            modelBuilder.Entity("familyTreeApi.Models.Users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAdminAccess")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("DeletedUserId");

                    b.HasIndex("ModifiedUserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2024, 11, 23, 10, 14, 15, 406, DateTimeKind.Utc).AddTicks(14),
                            EmailAddress = "admin@gmail.com",
                            HasAdminAccess = true,
                            IsDeleted = false,
                            Name = "Admin",
                            Password = "Test@123",
                            Status = "Active",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("familyTreeApi.Models.UserRelations", b =>
                {
                    b.HasOne("familyTreeApi.Models.Users", "CreatedUserFk")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("familyTreeApi.Models.Users", "DeletedUserFk")
                        .WithMany()
                        .HasForeignKey("DeletedUserId");

                    b.HasOne("familyTreeApi.Models.Users", "ModifiedUserFk")
                        .WithMany()
                        .HasForeignKey("ModifiedUserId");

                    b.HasOne("familyTreeApi.Models.Relations", "RelationFk")
                        .WithMany()
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("familyTreeApi.Models.Users", "UserFk")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUserFk");

                    b.Navigation("DeletedUserFk");

                    b.Navigation("ModifiedUserFk");

                    b.Navigation("RelationFk");

                    b.Navigation("UserFk");
                });

            modelBuilder.Entity("familyTreeApi.Models.Users", b =>
                {
                    b.HasOne("familyTreeApi.Models.Users", "CreatedUserFk")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("familyTreeApi.Models.Users", "DeletedUserFk")
                        .WithMany()
                        .HasForeignKey("DeletedUserId");

                    b.HasOne("familyTreeApi.Models.Users", "ModifiedUserFk")
                        .WithMany()
                        .HasForeignKey("ModifiedUserId");

                    b.Navigation("CreatedUserFk");

                    b.Navigation("DeletedUserFk");

                    b.Navigation("ModifiedUserFk");
                });
#pragma warning restore 612, 618
        }
    }
}
